### PR TITLE
#31 Fails to build with Xcode 13

### PR DESCRIPTION
**Pull request by kikeenrique**
+ Fix compilation error updating SwiftSyntax

Signed-off-by: Enrique Garcia <github@lemambo.com>

### CODE REVIEW

**Comment by DD-P** [comment]
Does the fatalError block in File.swift need to be updated to indicate Swift 5.5, as per the adjacent comment?

**Comment by kikeenrique** [comment]
Yes, you're right, in fact I should have read the comment in the line above my change.
I would add the change ASAP.

**Comment by kikeenrique** [comment]
I've think of another approach to support more than one swift version at a time.
I've tested it with Xcode 13 and Xcode 12.5.1, both compiling without errors.
What do you think?

**Comment by twostraws** [comment]
I love this – thank you so much!

**Pull request merged**
