### PR TITLE
Added JSON output format support

### PR DESCRIPTION
**Pull request by tib**
Hi Paul,

I've got some changes for Sitrep:
- Support for basic command line flags
- A new JSON report format is implemented (--json)
- Altered the text output to use the `Report` object values
- Removed the specific view count inheritance properties from the result
(Report generator has a better solution now, plus I think they were not working properly)
- Fixed some unit tests (two count numbers where always failing for me)
- Updated README.md

Please check my PR & have a nice weekend! 😉

Cheers,
Tib

### CODE REVIEW

**Comment by twostraws** [comment]
This is a great set of changes – thank you! In the future, could you split up changes into individual PRs so they make for easier review? It helps my brain if I'm only looking at one task at a time 🙂

I'm not going to merge these changes yet, because I'm keen to retain the inheritance checks if possible. I'm not sure why they would be failing, because they are pretty simple things. Could you perhaps give me an example where they fail so we could work to fix it?

**Comment by tib** [comment]
Sure, no problem, I can submit smaller PR's later on. I think this one contains more smaller changes, but they really depend on each-other. 🙃

Consider the following examples:

```
import SwiftUI

class View {
}

class A: View {
}

class B: SwiftUI.View {
}

/*
// original report:
SwiftUI Views: 0

// new report:
Inheritance:
   ---
   SwiftUI.View: 1
   View: 1
*/
```

or a more simple use case:

```
import SwiftUI

class C: NSObject, View {
}

// original report:
// SwiftUI Views: 0
```

Relying on the `.first` member of the inheritance chain is not a good way to count protocol inheritances, it can work with classes tho, but I'd rather check everything in the array.
```
/// How many structs conform to View
var swiftUIViewCount: Int {
    structs.sum { $0.inheritance.first == "View" }
}
```

That's why I logged everything from the inheritances. I know it's far from perfect, because of the namespace prefixes (eg. SwiftUI.View), but still it's a little bit more reliable solution than the one before. What do you think? 😅

**Comment by twostraws** [comment]
By the sounds of it, the best solution here is not to remove the current view / view controller inheritances, but just to modify what we have. For `UIView` and `UIViewController` we're safe, because they both need to come first in the list. For `View` – although it will rarely be `SwiftUI.View` (who writes that?), and it will almost always be the first in the list – there's no reason why we couldn't write some code to make it more accurate.

**Comment by tib** [comment]
Ok, fair enough. Is it ok if I revert back these 3 properties & log only the stats based on those in the report? So the core functionality won't change, but we can still have the JSON output.

**Comment by twostraws** [comment]
Yes, that would be ideal.

**Comment by twostraws** [comment]
Fantastic – thank you!

**Pull request merged**
